name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: rootproject/root:6.26.06-ubuntu22.04

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make test
      run: make test
