name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    container:
      image: rootproject/root:6.26.06-ubuntu22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install git
      run: apt-get install -y git
    - name: make
      run: make
    - name: make test
      run: make test
